#!/bin/zsh
open -a "$(find /Applications ~/Applications /System/Applications /System/Library/CoreServices/ -maxdepth 2 -name "*.app" | xargs -L1 -I{} basename "{}" .app | sort -n | fzf )" "$@" &> /dev/null
