#!/bin/zsh

########################################################
# Use strings below instead of 'spot apps' to use ls instead of mdfind
#
# ls -d \
# /Applications/*.app ~/Applications/*.app \
# /System/Applications/*.app \
# /System/Library/CoreServices/*.app \
# -maxdepth 2 -name "*.app" -s -nocolor \
########################################################

mdfind 'kMDItemContentType == "com.apple.application-*"' \
| fzf --no-info --no-sort --delimiter / --with-nth -1 --listen 6267 \
--bind 'alt-c:execute-silent(echo {} | pbcopy)+track' \
--bind 'alt-r:execute-silent(open -R {})' \
--bind 'esc:clear-query+clear-selection' \
--bind 'enter:execute-silent(yabai -m window --focus recent; open -a {})+clear-query+clear-selection' \
; exit
