#!/bin/zsh

########################################################
# Use strings below instead of 'spot apps' to use ls instead of mdfind
#
# ls -d \
# /Applications/*.app ~/Applications/*.app \
# /System/Applications/*.app \
# /System/Library/CoreServices/*.app \
# -maxdepth 2 -name "*.app" -s -nocolor \
########################################################

open -a "$(spot apps \
| xargs -L1 -I{} basename "{}" .app \
| fzf --no-info --no-sort \
--bind 'enter:execute-silent(open -a {})+track+clear-query')" \
"$@";exit &> /dev/null
